### ISSUE TITLE
Automatically rebuild & release images

### ISSUE THREAD

**Issue by bastelfreak** [archlinux/arch-boxes#1]
We should be able to do releases through travis:
https://docs.travis-ci.com/user/deployment/atlas/

Arch is a fast moving distribution, so it would be great to always have up2date boxes. Travis now offers cron jobs, which allows us to do releases on a weekly or daily basis:
https://docs.travis-ci.com/user/cron-jobs/

Let me know if you're interested in this, I'm happy to help.

**Comment by shibumi** [comment]
I have checked that.. travis can't automatically build vagrant images.. it can only deploy to atlas..
So my current idea is a little script that starts packer with headless providers and uploads the boxes directly to atlas without travis in between. What do you think?

**Comment by rafaelsoaresbr** [comment]
@shibumi Do you want to configure Vagrant Cloud Post-Processor to automatically upload the Boxes?

**Comment by shibumi** [comment]
In the future yes

**Comment by shibumi** [comment]
First automated release is out: https://app.vagrantup.com/archlinux/boxes/archlinux/versions/2017.09.07
