### ISSUE TITLE
[Bug] Missing virtualbox provider for version 2020.05.04

### ISSUE THREAD

**Issue by Jiehong** [archlinux/arch-boxes#100]
All boxes in https://app.vagrantup.com/archlinux/boxes/archlinux are usually provided for 2 providers: libvirt and virtualbox.

However, the latest (2020.05.04), is only published for the libvirt provider.

Would it be possible to also publish it for the virtualbox provider?

**Comment by shibumi** [comment]
This sounds like an error.. I will have a look into this, thanks!

**Comment by shibumi** [comment]
Thanks, this is indeed a bug:

 ==> virtualbox-iso: error: target not found: virtualbox-guest-modules-arch

**Comment by shibumi** [comment]
@Jiehong new virtualbox has been deployed. I will fix the bug in the meanwhile.

**Comment by shibumi** [comment]
Already fixed a month ago, just not deployed yet.
