### ISSUE TITLE
[Question] Desktop resizing?

### ISSUE THREAD

**Issue by PaulWalkerUK** [archlinux/arch-boxes#103]
I had a Vagrant/VirtualBox VM built from this base box working fine at the back end of 2019. When I recently `vagrant destroy/vagrant up`'d it, desktop resizing no longer worked. Unfortunately, my previous instance of the VM was around for a while and not updated much, so there was plenty of time for various things to change that could have affected it.

I'm just raising this question here because I see a [few tickets](https://github.com/archlinux/arch-boxes/issues?q=vboxvga+OR+vmsvga+created%3A%3E2019-11-01+) in the right sort of time frame that could relate to this area. Is anyone else using this base box successfully with desktop resizing?

**Comment by shibumi** [comment]
The vmsvga patches got never applied or got reverted, in this time no box has been generated. I actually doubt that your issues have something to do with these tickets, but feel free to prove me wrong :)

I'll leave this question open, maybe someone will see it and has an idea.

**Comment by PaulWalkerUK** [comment]
No problem - I'll keep hunting, thanks

**Comment by shibumi** [comment]
You could check if the virtualbox extras are installed in the box and operational. At least this would be one of the first things I would check.

**Comment by PaulWalkerUK** [comment]
I may have found what broke it: looks like there may be an [issue with Guest Additions 6.1.6](https://www.virtualbox.org/ticket/19496).

Happy to close this here now. Thanks for your help 😄
