### ISSUE TITLE
Output virtualbox and qemu images as additional artifacts 

### ISSUE THREAD

**Issue by shibumi** [archlinux/arch-boxes#11]
We want to have additional virtualbox and qemu images that we can host on archlinux.org.
I guess this will need some changes in the vagrant.json file

**Comment by rafaelsoaresbr** [comment]
We can setup a [Local Shell Post Processor](https://www.packer.io/docs/post-processors/shell-local.html) to upload the boxes to archlinux.org.

**Comment by shibumi** [comment]
Well, no. We will just run the whole build process on of the arch linux servers so they will automatically build the boxes and images once a week.

**Comment by shibumi** [comment]
Done with 0b11b16f39c8e67d7f434b94dd33c3c74530a6f8 -> `keep_input_artifacts`
