### ISSUE TITLE
Include sshfs and/or rsync

### ISSUE THREAD

**Issue by aidanharris** [archlinux/arch-boxes#14]
Could you please include sshfs and/or rsync. For me they both fail to install on a `vagrant up` (I'm using the libvirt provider in case it makes a difference) presumably because a `pacman -Syu` is needed first?

These aren't very large so shouldn't bloat the image too much. According to `pacman -Qi sshfs` its installed size is 76.00 Kib and according to `pacman -Qi rsync` its installed size is 531.00 Kib (note: this probably doesn't factor in any other libraries that are pulled in with it but these probably aren't that large?).

**Comment by shibumi** [comment]
Why does it fail for you when you install it? Can you provide an error log or something?

**Comment by aidanharris** [comment]
Here's the relevant bit from a `VAGRANT_LOG=debug vagrant up --provider libvirt`

```sh
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: sshfs_install
DEBUG guest: Checking in: arch
DEBUG guest: Found cap: sshfs_install in arch
 INFO guest: Execute capability: sshfs_install [#<Vagrant::Machine: master (VagrantPlugins::ProviderLibvirt::Provider)>] (arch)
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: pacman --noconfirm -S sshfs (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from archlinux.cu.be : The requested URL returned error: 404

 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from mirror.metalgamer.eu : The requested URL returned error: 404

DEBUG ssh: Sending SSH keep-alive...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from arch.softver.org.mk : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from mirror.united-gameserver.de : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from mirror.netcologne.de : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'fuse-common-3.0.2-1-x86_64.pkg.tar.xz' from arch.jensgutermuth.de : The requested URL returned error: 404
warning: failed to retrieve some files

 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from archlinux.cu.be : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from mirror.metalgamer.eu : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from arch.softver.org.mk : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from mirror.united-gameserver.de : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from mirror.netcologne.de : The requested URL returned error: 404

DEBUG ssh: stderr: error: failed retrieving file 'sshfs-2.9-1-x86_64.pkg.tar.xz' from arch.jensgutermuth.de : The requested URL returned error: 404

DEBUG ssh: stderr: warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)

DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The install of the sshfs client software failed. On Arch this is most likely
because the package lists are not up to date [1] and partial upgrades are not
supported [2]. Please update your Arch system or install SSHFS manually.
```

Basically the pacman cache isn't up to date so pacman tries to install sshfs and fails appropriately. I see a few ways to fix this:

1) Fix this in vagrant-sshfs (Installing it via `pacman -Sy sshfs` would probably work?)
2) Release updated images on a daily basis thereby guaranteeing that the pacman cache will be up to date
3) Update the pacman cache on boot somehow?
4) Include these utilities in the base image so that they don't need to be manually installed. This would add some slight bloat but add practicality since most people are probably going to install these tools anyway.

**Comment by shibumi** [comment]
Well, we clean the pacman cache on purpose. We do that for reducing the size of the images. 
Just use `pacman -Syu sshfs` for installing new software. (it's also recommended in the Arch Linux Wiki. Never do `pacman -S` this is not encouraged)

To your points.

1. Just use `pacman -Syu` for installing new packages.
2. These builds are supposed to be a mirror of the monthly live-ISO releases. We are thinking about daily builds for testing.
3. You can update the pacman cache on boot via: `pacman -Syy` You can pack this commands in your vagrant file to provision the image before the first boot. Or use a configuration management tool like `ansible` or `puppet`.
4. Sorry we will not add additional software. We want to keep the image as small as possible. If we would listen to all package suggestions we would have totally bloated package in the end. I hope you understand this.

**Comment by shibumi** [comment]
Closing this issue. I think everything is said. If you need more help, just reply.
