### ISSUE TITLE
Make minimizing of images via writing zeroes to free space optional

### ISSUE THREAD

**Issue by shibumi** [archlinux/arch-boxes#18]
The minimizing of images via writing zeroes to free spaces *must* be optional to reduce wear and tear.
See also: https://github.com/archlinux/arch-boxes/pull/17

**Comment by appleby** [comment]
It should be possible to move the zeroing of the disk into a separate provisioner that's guarded with a packer user variable, like so:

https://www.packer.io/docs/templates/user-variables.html#making-a-provisioner-step-conditional-on-the-value-of-a-variable

I guess it doesn't hurt to give user's the ability to opt-out, but there is also the question of whether ssd wear with the change in #17 is a real or just a perceived problem. I don't really know anything about ssd wear, but I suspect the answer is complicated and depends on the user's hardware, drive settings, and how often they run these builds.  Are you running 100 builds a day every day? Maybe it matters. Are you running one or two builds a month? Maybe it doesn't.

**Comment by rafaelsoaresbr** [comment]
So, we can move that piece of code to another script and add a new provisioner that runs on all builders.

**Comment by appleby** [comment]
Exactly.

I think you could also modify the shell provisioner's execute_command to pass in the user vars into the environment where the shell script executes, and just have a conditional check in `cleanup.sh` if you want to avoid adding a separate script.

Personally, I would go with adding a new script and provisioner as it makes it clear in `vagrant.json` that the disk zeroing is optional.

**Comment by shibumi** [comment]
@rafaelsoaresbr exactly thats the plan ;)

**Comment by shibumi** [comment]
I hope https://github.com/archlinux/arch-boxes/commit/2311382af0eb15a04e71137fe102acdc3448c84b will fix the issue..
