### ISSUE TITLE
Error occurred when following the build process in README

### ISSUE THREAD

**Issue by ishbguy** [archlinux/arch-boxes#26]
When following the build process in README, I got this error:

```bash
$ packer-io build vagrant.json
qemu output will be in this color.
virtualbox-iso output will be in this color.
vmware-iso output will be in this color.

1 error(s) occurred:

* open /srv/ftp/iso/latest/sha1sums.txt: no such file or directory
```
So I read the `vagrant.json`, I found that I need to pass the `iso_url` and `iso_checksum_url` variables to packer when I build a boex without a local ISO image.

Could you update the README's build process section to make it more detail? Because I think it is good for someone new to get start :).

**Comment by shibumi** [comment]
Hi,
You are right, the README is currently outdated. If you want to build local on your own machine you need to change the variables in the `vagrant.json` file or via commandline. 

Can I ask why you want to build the boxes by yourself? You can easily download them from vagrantcloud.com via:
```
vagrant init archlinux/archlinux
vagrant up
```

Please check also the "write_zeros" variable. If you use this variable on a computer with SSD it can affect your SSDs lifetime.

**Comment by ishbguy** [comment]
Yep, I am a Chinese guy, I have tried to download the archlinux box from the offical vagrantcloud.com, but I found that the network is too slow to do it. So I try to build my own boxes on local machine, then I find this great repo while reading the vagrant wiki from wiki.archlinux.org, thanks for your work.

**Comment by shibumi** [comment]
@ishbguy I have added a `local.json` file and updated the README. You can use the `local.json` file to build the box locally. Please read the README to get to know how to do this.

**Comment by ishbguy** [comment]
Thanks.
