### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by jbonigomes** [archlinux/arch-boxes#27]
I am having an issue booting the VM when using a private network, sometimes the box boots just fine but very often, the booting process (vagrant up) times out on this step:

default: SSH auth method: private key

Booting the box from a Windows 10 host, Virtual Box v5.1.22 and Vagrant v2.0.0.

**Comment by shibumi** [comment]
Ok this sounds odd. Maybe it has something todo with our default ssh key pair. But vagrant should be able to automatically replace it:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/chris
```

**Comment by jbonigomes** [comment]
Seems like it works for you with no problems, do you think it may be related to some misconfiguration in my PC? Do you have any suggestions that could help me narrow the problem down?

**Comment by shibumi** [comment]
@jbonigomes You can try to upgrade to vagrant 2.0.4 you are 4 releases behind. Maybe they have fixed something in this time.

**Comment by jbonigomes** [comment]
Thanks @shibumi unfortunately, due to ISO security reasons, the company I work for is very careful with updates. However what you are saying couldn’t sound more right. I will try to work my magic with them. Closing the issue for now. Thanks a lot for looking into it.

**Comment by shibumi** [comment]
@jbonigomes Keep me updated. ;) Would be nice to know if this is fixed in the future or not.

**Comment by jbonigomes** [comment]
Thanks, will do

**Comment by jbonigomes** [comment]
Hi, @shibumi just wanted to let you know, I now managed to update to Vagrant 2.1.1 along with Virtual Box 5.2.12 and it all works fine.
