### ISSUE TITLE
fault tolerance 

### ISSUE THREAD

**Issue by shibumi** [archlinux/arch-boxes#33]
We cannot rely on stable and continuous ISO image builds, therefore we have to build vagrant boxes fault tolerant. Instead of evoking the packer command via systemd service on a specific date, we should evoke a small program every day and check for the newest release.

**Comment by ladar** [comment]
If I understand what your trying to do, these [lines](https://github.com/lavabit/robox/blob/3aa19447cd5524d6d423e7a32ad5404450ee22bf/robox.sh#L154-L159) from my [robox.sh](https://github.com/lavabit/robox/blob/3aa19447cd5524d6d423e7a32ad5404450ee22bf/robox.sh) script should help:

```bash
  tput setaf 2; printf "\nArch\n\n"; tput sgr0;
  URL="https://mirrors.edge.kernel.org/archlinux/iso/latest/"
  ISO=`curl --silent "${URL}" | grep --invert-match sha256 | grep --extended-regexp --only-matching --max-count=1 "archlinux\-[0-9]{4}\.[0-9]{2}\.[0-9]{2}\-x86\_64\.iso" | uniq`
  URL="${URL}${ISO}"
  SHA=`curl --silent "${URL}" | sha256sum | awk -F' ' '{print $1}'`
printf "${URL}\n${SHA}\n\n"
```

This will locate the latest release, download it and print the URL/SHA for the installer. I scripted the process to make updating my templates easier.
