### ISSUE TITLE
Is it realy necessary to install linux-headers?

### ISSUE THREAD

**Issue by rafaelsoaresbr** [archlinux/arch-boxes#4]
Is there any reason to install `virtualbox-guest-utils-nox` + `linux-headers` instead of `virtualbox-guest-utils-nox` + `virtualbox-guest-modules-arch`?

**Comment by shibumi** [comment]
good question. I thought `linux-headers` is necessary for the use of the virtualbox modules.  I would also go with `virtualbox-guest-dkms` instead of `virtualbox-guest-modules-arch`. I think I will include this in the next release

**Comment by Barthalion** [comment]
Why kernel headers would be necessary? Just stick to `virtualbox-guest-modules-arch`. Using DKMS will only make the image bigger and startup slower.

**Comment by rafaelsoaresbr** [comment]
Exactly @Barthalion. My suggestion it to remove `linux-headers` and `virtualbox-guest-dkms` and include `virtualbox-guest-modules-arch`. For `linux` kernel there is no need to use DKMS at all.

**Comment by rafaelsoaresbr** [comment]
Sorry, I've fixed.
