### ISSUE TITLE
pacman upgrades don't work after installing the latest vagrant image

### ISSUE THREAD

**Issue by gun1x** [archlinux/arch-boxes#48]
**Describe the bug**
After installing from the image tagged `2019.08.05`, the pacman upgrade gets stuck on `error: archlinux-keyring: signature from` and almost every key fails.

**To Reproduce**
Deploy `archlinux/archlinux` with vagrant and try to run `pacman -Syu`

**Expected behavior**
I expected an install.

**Host Software (please complete the following information):**
qemu, libvirt, vagrant

**Additional context**
sovled by running
```
pacman-key --refresh-keys
pacman -Sy archlinux-keyring
pacman -Su
```

**Comment by shibumi** [comment]
Duplicate to: https://github.com/archlinux/arch-boxes/issues/41
