### ISSUE TITLE
Remove swap?

### ISSUE THREAD

**Issue by rafaelsoaresbr** [archlinux/arch-boxes#5]
I would remove swap partition and let the users create it (swapfile, systemctl mask tmp.mount...) on their own the same way ubuntu's official boxes do.

**Comment by shibumi** [comment]
@rafaelsoaresbr The filesystem is btrfs. A swapfile on a btrfs filesystem is not a good idea..

**Comment by rafaelsoaresbr** [comment]
Yes I known, but maybe you could use a LVM setup. Thank you, good work!

**Comment by shibumi** [comment]
I don't think that a LVM setup would be an enhancement. It's just a dev box.. We should keep it simple,
