### ISSUE TITLE
Box will not boot with libvirt and graphics_type=none

### ISSUE THREAD

**Issue by njfox** [archlinux/arch-boxes#67]
**Describe the bug**
The arch box will not boot when setting`graphics_type=none` when using the `vagrant-libvirt` provider. It gets stuck waiting for an IP address, but if you remove this option and let `vagrant-libvirt` use the default setting of vnc, the box will boot normally.

**To Reproduce**
Using vagrant-libvirt as your provider, set the `graphics_type` option to `none` and run `vagrant up`. Here is the relevant snippet from my Vagrantfile:

```
    a64.vm.provider "libvirt" do |lv, override|
      override.vm.network "private_network",
        :libvirt__network_name => "trusted", # modify to fit your virtual network setup
        :libvirt__netmask => "255.255.255.0"
      # Sync a folder between the host and all guests.
      # Uncomment this line (and adjust as you like)
      # NOTE: Requires installation of the nfs-server package on the host machine
      # If `vagrant up` hangs at Mounting NFS folders, modify your firewall configuration
      # to allow nfs, rpc, and mountd services
      override.vm.synced_folder "~/ctf", "/ctf", :nfs => true
      override.vm.hostname = name
      lv.memory = memory
      lv.graphics_type = "none"
```

**Expected behavior**
The box boots normally with `graphics_type = "none"` set.

**Host Software (please complete the following information):**
 - OS: Linux
 - Distribution: Arch LInux
 - Vagrant Version: 2.2.6
 - Hypervisor: libvirt (KVM/QEMU backend)
 - Hypervisor Version: libvirt: 5.8.0, QEMU 4.1.0
 - Image Version: 2019.10.02
 - Host Modules: `kvm`, `virtio`
 - Host Modules Version: n/a
 - Output of `id` command: `uid=1000(nick) gid=1000(nick) groups=1000(nick),56(bumblebee),972(libvirt),986(video),988(storage),998(wheel)`
 - Output of `uname -a`: `Linux hexps-ng 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux`

**Additional context**
I also tried additionally setting the `video_type = "none"` option to remove the video device but got the same behavior.

**Comment by shibumi** [comment]
Hi @njfox 
Normally you don't need to set `graphics_type = none`. If you just do `vagrant init archlinux/archlinux && vagrant up && vagrant ssh` you should have a headless VM without a GUI.

**Comment by njfox** [comment]
Thanks for the reply. According to vagrant, if I remove `graphics_type=none`, it launches with `graphics_type=vnc` since [that's the default](https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options) for vagrant-libvirt. Do you have any suggestions for a workaround to make it truly headless with this provider?

**Comment by shibumi** [comment]
Could you please provide the information from the bug ticket? (I know it's tedious and I hate such bug templates very often as well, but they help a lot):
```
name: Bug report
about: Create a report to help us improve
title: "[Bug]"
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Host Software (please complete the following information):**
 - OS: [e.g. Linux]
 - Distribution: [e.g. Arch Linux]
 - Vagrant Version: [`vagrant version`]
 - Hypervisor: [e.g Virtualbox]
 - Hypervisor Version: [e.g. Virtualbox Version]
 - Image Version: [e.g. v2019.07.05]
 - Host Modules: [e.g. virtualbox-host-dkms]
 - Host Modules Version: [e.g. 6.0.10-1]
 - Output of `id` command: [this is for checking if your user is part of group `vboxusers`]
 - Output of `uname -a`: [e.g. Linux motoko 5.2.11.a-1-hardened #1 SMP PREEMPT Tue Sep 3 00:13:50 CEST 2019 x86_64 GNU/Linux]

**Additional context**
Add any other context about the problem here.
```

**Comment by shibumi** [comment]
I am especially interested in the information in "Host Software"

**Comment by njfox** [comment]
No worries--I've updated the original post with the bug report template.

**Comment by njfox** [comment]
After doing some further research and playing around with non-vagrant images, it looks like Linux in general requires substantial configuration to be able to boot without any video device (TIL). It sounds like libvirt just presents these options differently than virtualbox (and makes them appear optional).

I’m closing this thread because I don’t think this is a specific issue with the archlinux box. Thanks for your help!

**Comment by shibumi** [comment]
@njfox if you find a solution for this, please update this thread :) I would like to add this to the README section, maybe as a "FAQ" or "Troubleshooting"

**Comment by njfox** [comment]
Will do, although at this point I suspect Vbox is adding a similar vnc video device under the hood when gui is set to none, so it seems like a reasonable workaround to just let libvirt use it as well. The overhead is probably minimal

**Comment by shibumi** [comment]
@njfoxcan you  provide the full libvirt XML file? This could give a hint. ^^ Actually I doubt that it's the guests fault.

**Comment by njfox** [comment]
Here is the XML with just the `graphics_type = "none"` option set:

```
<domain type="kvm">
  <name>pwnvm-arch_testing</name>
  <uuid>7bbc4e84-df51-48ed-95ce-6653ae855399</uuid>
  <memory unit="KiB">2097152</memory>
  <currentMemory unit="KiB">2097152</currentMemory>
  <vcpu placement="static">1</vcpu>
  <os>
    <type arch="x86_64" machine="pc-i440fx-4.1">hvm</type>
    <boot dev="hd"/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode="host-model" check="partial">
    <model fallback="allow"/>
  </cpu>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="/home/nick/libvirt/storage/pwnvm-arch_testing.img"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/>
    </disk>
    <controller type="usb" index="0" model="piix3-uhci">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x2"/>
    </controller>
    <controller type="pci" index="0" model="pci-root"/>
    <interface type="network">
      <mac address="52:54:00:54:f6:df"/>
      <source network="vagrant-libvirt"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x0"/>
    </interface>
    <interface type="network">
      <mac address="52:54:00:ad:95:13"/>
      <source network="trusted"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x05" function="0x0"/>
    </interface>
    <serial type="pty">
      <target type="isa-serial" port="0">
        <model name="isa-serial"/>
      </target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"/>
    </console>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0"/>
    </memballoon>
  </devices>
</domain>
```

**Comment by grazzolini** [comment]
@njfox, if I recall correctly, the last time I tried to boot an Arch box with graphics=none, I needed to disable all KMS, also pass vga=none. The Arch kernel requires *some* output. You can try to add a serial console to your VM too. Another thing you might want to try, is to switch to Q35. It does the video initialization on the VM differently.

**Comment by njfox** [comment]
Great, thanks for the info--that makes sense based on my understanding. I'm going to just stick with the defaults (vnc) since having a console might end up being helpful for troubleshooting in some situations

**Comment by grazzolini** [comment]
@njfox, if you don't plan on running X/Wayland, a serial console is fine. See here for reference on how to use one on Arch: https://wiki.archlinux.org/index.php/Working_with_the_serial_console

**Comment by njfox** [comment]
Those configuration changes would have to be made to the base box to be able to provision it with no video device correct?

**Comment by grazzolini** [comment]
@njfox You mean to arch-boxes itself? Not sure, @shibumi can help there. But you can override stuff locally and/or build them yourself. I've built some images for myself using packer.json.
