### ISSUE TITLE
[BUG] netctl missing for IP configuration

### ISSUE THREAD

**Issue by juadde** [archlinux/arch-boxes#70]
When using archlinux vagrant boxes hostonly static IP assgnation is failing.

**To Reproduce**
1. Use following Vagrantfile
`Vagrant.configure("2") do |config|`
`  config.vm.box = "archlinux/archlinux"`
`  config.vm.network "private_network", ip: "192.168.0.50"`
`end`
2. Run `vagrant up` (tested with virtualbox as backend)
3. See error
`==> default: Configuring and enabling network interfaces...`
`The following SSH command responded with a non-zero exit status.`
`Vagrant assumes that this means the command failed!`
`# Configure eth1`
`mv '/tmp/vagrant-network-eth1-1576228056-0' '/etc/netctl/eth1' &&`
`ip link set 'eth1' down &&`
`netctl restart 'eth1' &&`
`netctl enable 'eth1'`
`Stdout from the command:`
`Stderr from the command:`
`mv: cannot move '/tmp/vagrant-network-eth1-1576228056-0' to '/etc/netctl/eth1': No such file or directory`

**Expected behavior**
Expected ip: "192.168.0.50" assigned instead of:
`3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000`
`    link/ether 08:00:27:11:75:00 brd ff:ff:ff:ff:ff:ff`

**Host Software (please complete the following information):**
 - OS: Windows
 - Distribution: 10 Pro
 - Vagrant Version: 2.2.6
 - Hypervisor: Virtualbox
 - Hypervisor Version: 6.0.14
 - Image Version: 2019.12.02
 - Host Modules: N/A
 - Host Modules Version: N/A
 - Output of `id` command: N/A
 - Output of `uname -a`: N/A
 - Vagrant Plugins: vagrant-reload (0.0.1, global) [Not used], vagrant-vbguest (0.20.0, global) [Disabled through config.vbguest.auto_update = false in Vagrantfile], vagrant-windows-update (0.0.7, global) [Not relevant here I guess]

**Additional context**
I don't know if it is a bug or not, but once netctl is installed the behavior is the good one, static IP is assigned as expected.

**Comment by shibumi** [comment]
Thank you so much for reporting this. I actually didn't know that vagrant has distribution specific plugins for various jobs like SMB, Network, etc. 

Looks like vagrant tries to set up the network via `netctl`: https://github.com/hashicorp/vagrant/blob/85acf0cac724ef4bfda593a66e0c17f7e4110da0/plugins/guests/arch/cap/configure_networks.rb#L42L49

I have to admit, that I am not a big fan of netctl, I consider it as outdated and nobody should use it. `systemd-networkd` is the way to go to configure ethernet devices.

I am going to add `netctl` as dependency for the next arch boxes release, but the better solution on long term is to replace `netctl` with `systemd-networkd` in the vagrant plugins. I will have a look on the vagrant plugins for arch linux as well for making sure, that we are not lacking other tools.

**Comment by frenchy64** [comment]
I'm new to Arch networking and Vagrant, but I needed a "public_ip" using DHCP from a Virtualbox VM. Here's how I worked around this issue, which worked well enough for my purposes (MBP host).

# Vagrantfile

```sh
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  # Run `ip addr` to find assigned IP address for guest
  config.vm.provider "virtualbox" do |vb, override|
    override.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)", auto_config: false
    override.vm.provision "shell", path: "request-ip.sh"
  end
end
```

# request-ip.sh

```sh
#!/bin/bash

set -o nounset
set -o errexit

pacman -Sy --noconfirm --needed iproute2 dhcpcd

# request IP address
dhcpcd -k eth1 || true
dhcpcd eth1
```

**Comment by rmunn** [comment]
https://github.com/hashicorp/vagrant/pull/11400 will change Vagrant's Arch plugin to use `systemd-networkd` once it's merged and released. Subscribe to that PR if you want to be notified when it gets merged into Vagrant.

**Comment by shibumi** [comment]
Good News @juadde https://github.com/hashicorp/vagrant/issues/11254 has been finally fixed.
One stop closer away from netctl.
