### ISSUE TITLE
[RFE] Switch from VBoxVGA graphic controller to VMSVGA for Virtualbox boxes

### ISSUE THREAD

**Issue by juadde** [archlinux/arch-boxes#73]
**Problem**
In Virtualbox we can see a parameter is detected as invalid since virtualbox >6.0:
![VBoxVGA](https://user-images.githubusercontent.com/29175532/71826015-47c03900-309d-11ea-8bcb-7c3b7b7f792d.png)
(Sorry for the screen in semi-French)

And the box seems to work fine with the following setting:
![VMSVGA](https://user-images.githubusercontent.com/29175532/71828263-4e9d7a80-30a2-11ea-90a7-403d988f8871.png)

**Solution**
Maybe providing the box directly with the "good" driver would ease its usage.

**Describe alternatives you've considered**
An easy workaround is to add this line in the virtualbox section of the Vagrantfile:
`vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']`

**Additional context**
This selection of drivers is new in virtualbox 6.0 (https://superuser.com/questions/1403123/what-are-differences-between-vboxvga-vmsvga-and-vboxsvga-in-virtualbox).
I do not know if this setting would have an impact on "old" Virtualbox installations (<6.0).
For Xorg to work "properly" with VMSVGA, xf86-video-vmware is needed (however automatic resizing does not appear to work, unlike vbox[s]vga).

**Comment by shibumi** [comment]
Hi,
sorry for the late reply. I wonder that vagrant doesn't take care of this. Is vagrant expecting an older virtualbox version? Right now we are not shipping a vagrantfile and let vagrant generate it for us, this would need some tweaks in our packer configuration + further testing. If you want to implement this, I would be happy to merge it and give it a try.

**Comment by juadde** [comment]
Hi,
That's a good question for the virtualbox version, I will perform some tests as I already have a local.json that build boxes which provides VMSVGA driver and an old Virtualbox installed. I will submit a PR if I get something consistent, one thing I need to figure out is how to pass the driver value so it can be used like the cpus with the {{user `cpus`}} notation (seems that I am missing to declare it in a map somewhere).

**Comment by juadde** [comment]
Closed by  #75
