### ISSUE TITLE
[Bug] Packer validation failing on Github actions

### ISSUE THREAD

**Issue by juadde** [archlinux/arch-boxes#76]
**Describe the bug**
Packer validation on iso checksums failed, however everything was fine during the PR.

**To Reproduce**
Look at the readme badge status "failed" 

**Expected behavior**
A green badge on the readme.

**Links**
https://github.com/archlinux/arch-boxes

**Host Software (please complete the following information):**
Any browser

**Additional context**
I did some changes on the json file in #75 but they were meant to run well as they ran fine during #75 PR, and from what I see in the [logs](https://pipelines.actions.githubusercontent.com/0fkhxXGS7b9Pk4XHrgpvdP70R4SWMdzz2SSqFgQghYtb7ZU4lK) the values taken into account (iso_url & iso_checksum_url) seems overwritten by the Github action anyway.
Maybe a re-run would suffice?

**Comment by shibumi** [comment]
Was an issue with github actions. Not our bug.
