### ISSUE TITLE
[Question] Warn X11 Users for vmsvga driver

### ISSUE THREAD

**Issue by juadde** [archlinux/arch-boxes#77]
Hello I wanted to add a warning for the box users with this kind of text:

### X11 doesn't work on Virtualbox
As Virtualbox recommendation is to used vmsvga driver, this is what has
been done on this box, however this driver is available through 
[xf86-video-vmware](https://www.archlinux.org/packages/extra/x86_64/xf86-video-vmware/).

Make sure it is installed as it is not included in the kernel.

You can still use the old graphic controller if you include this line
in the virtualbox section of the Vagrantfile:

`vb.customize ['modifyvm', :id, '--graphicscontroller', 'vboxvga']`

`vboxsvga` and `none` are also valid values.

I do not know where to put this, should it be on the readme.md  like I did on https://github.com/juadde/arch-boxes or should it be somewhere else like on the [wiki](https://wiki.archlinux.org/index.php/DeveloperWiki:arch-boxes).

Maybe my english is not good and the text needs to be modified to be more "english"...

**Comment by shibumi** [comment]
Mhh this is information that has been missing in your last PR. Wouldn't it make sense to revert your PR and keep shipping the boxes with the old graphicscontroller?

Alternative: We print a message via Vagrant: https://stackoverflow.com/a/36876622/3498573

**Comment by juadde** [comment]
Yes, let's rollback the PR to ship the old graphicscontroller, and we might want to print something in vagrant if some of the users wants to follow Virtualbox recommendations. I'll see how this can be done (thanks for the stackoverflow link).

**Comment by shibumi** [comment]
Fixed by #78
