### ISSUE TITLE
Reduce box's size

### ISSUE THREAD

**Issue by rafaelsoaresbr** [archlinux/arch-boxes#8]
I'm trying to make box's size as small as this [box](https://app.vagrantup.com/wholebits/boxes/archlinux)
For this, I'm trying to run fstrim in "cleanup.sh" instead of running dd like in that [box](https://github.com/wholebits/baseboxes/blob/master/scripts/archlinux.sh#L81-L96).
I'm going to test this tonight because I don't have a good internet connection.

**Comment by shibumi** [comment]
any update here?

**Comment by rafaelsoaresbr** [comment]
`fstrim` doesn't seen to work, I'm  going to try with `zerofill`.
