### ISSUE TITLE
[RFE] Support specifying a mirror used under the build

### ISSUE THREAD

**Issue by klausenbusk** [archlinux/arch-boxes#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the build takes forever, because it is using a slow mirror

**Describe the solution you'd like**
Add a new variable which is supplied to `install.sh` and used under the installation.

**Describe alternatives you've considered**
None

**Comment by shibumi** [comment]
This frustrates me, too. Do you have a good idea how we can solve this issue?

We could install reflector on the live iso and trigger that before triggering the install scripts.

**Comment by klausenbusk** [comment]
> This frustrates me, too. Do you have a good idea how we can solve this issue?

Maybe:
```diff
diff --git a/cloud.json b/cloud.json
index 92794be..b206ad3 100644
--- a/cloud.json
+++ b/cloud.json
@@ -8,7 +8,8 @@
         "cpus": "2",
         "headless": "true",
         "write_zeroes": "",
-        "boot_wait": "60s"
+        "boot_wait": "60s",
+        "mirror": ""
     },
     "builders": [
         {
@@ -40,7 +41,7 @@
             "boot_command": [
                 "<enter><wait10><wait10><wait10><wait10><wait10><enter><enter>",
                 "curl -O 'http://{{.HTTPIP}}:{{.HTTPPort}}/install{,-common,-cloud}.sh'<enter><wait>",
-                "bash install.sh < <(cat install-{cloud,common}.sh) && systemctl reboot<enter>"
+                "MIRROR=\"{{.MIRROR}}\" bash install.sh < <(cat install-{cloud,common}.sh) && systemctl reboot<enter>"
             ]
         }
     ],
diff --git a/http/install.sh b/http/install.sh
index e22be6c..e869e1c 100644
--- a/http/install.sh
+++ b/http/install.sh
@@ -25,7 +25,8 @@ mkswap "${device}1"
 mkfs.ext4 -L "rootfs" "${device}2"
 mount "${device}2" /mnt
 
-pacstrap /mnt base linux grub openssh sudo polkit haveged netctl python reflector
+echo "Server = ${MIRROR}" > /etc/pacman.d/mirrorlist
+pacstrap -M /mnt base linux grub openssh sudo polkit haveged netctl python reflector
 swapon "${device}1"
 genfstab -p /mnt >>/mnt/etc/fstab
 swapoff "${device}1"
```

> We could install reflector on the live iso and trigger that before triggering the install scripts.

Maybe we should do both? If `mirror` isn't specified run `reflector` else use the provided mirror.

**Comment by shibumi** [comment]
Setting a mirror should be enough. It's just for the build process.

We should just make sure to 'guard' the MIRROR variable that we don't set an empty mirror server accidentally:

```bash
if [ ! ${MIRROR} == "" ]; then
echo "Server = ${MIRROR}" > /etc/pacman.d/mirrorlist
fi
```

**Comment by klausenbusk** [comment]
PR opened #93
