### ISSUE TITLE
[Bug] Build timeout

### ISSUE THREAD

**Issue by juadde** [archlinux/arch-boxes#94]
**Describe the bug**
Build does not finish anymore with latest changes.

**To Reproduce**
1. Fetch latest master branch
2. run `packer build -only=virtualbox-iso local.json` or `packer build cloud.json`
3. Wait for ssh_timeout to end (> 2h)
4. Build does not finish

**Expected behavior**
Build should finish successfully.

**Screenshots & Logs**
VM does not restart, even if "systemctl reboot" is sent to the machine. The VMs is stuck here:
![Build](https://user-images.githubusercontent.com/29175532/75348010-4e4f7d80-58a2-11ea-86d1-6887a547819d.png)

Packer finishes with the following error:

`Build 'virtualbox-iso' errored: Timeout waiting for SSH.`
`==> Some builds didn't complete successfully and had errors:`
`--> virtualbox-iso: Timeout waiting for SSH.`
`==> Builds finished but no artifacts were created.`

**Host Software (please complete the following information):**
 - OS: Windows / Linux
 - Distribution: 10 Pro / Archlinux
 - Vagrant Version: 2.2.7
 - Packer: 1.5.4
 - Hypervisor: Virtualbox
 - Hypervisor Version: 6.1.4
 - Image Version: Current master branch
 - Output of `uname -a`: N/A
 - Vagrant Plugins: vagrant-reload (0.0.1, global), vagrant-timezone (1.3.0, global), vagrant-vbguest (0.20.0, global), vagrant-windows-update (0.0.7, global), vagrant_reboot_linux (1.0.0, global)

**Additional context**
Build is successful on those machines before the changes for the cloud scripts (Rebuilding the arch-box from an older commit is working properly).
I will investigate to get the exact commit where the build begin to fail and report here:
ea7869f1a82e51d188f6f820da3e986fa32101f2 is working properly.

Please let me know if anybody have a clue on what is happening.

**Comment by klausenbusk** [comment]
I haven't tried `packer build -only=virtualbox-iso local.json` but `packer build cloud.json` works, so this is weird.

Could you try running `arch-chroot /mnt /bin/bash -x < <(cat install-{cloud,common}.sh)` when `packer build cloud.json` get stuck?

**Comment by juadde** [comment]
OK, I'll try, for information until b9f0c26c4d491add37e2f57cbbea09fc4b1d2265 it is working properly

**Comment by juadde** [comment]
So I tried running `arch-chroot /mnt /bin/bash -x < <(cat install-{chroot,common}.sh)` in virtualbox but it complains about not having the files (`No such file or directory` for install-chroot.sh and install-common.sh). And after a `find / -name install-common.sh` as root it seems true that there is nothing there as I was in the chroot.

Exiting the chroot and running the command + rebooting the machine created the box.

**Comment by klausenbusk** [comment]
Could you watch the console of the machine and see what command it type? It should type ` bash install.sh < <(cat install-{cloud,common}.sh) && systemctl reboot`

**Comment by juadde** [comment]
Looks good no?

![bash](https://user-images.githubusercontent.com/29175532/75353467-c3738080-58ab-11ea-9a98-084f5e86ab9e.png)

**Comment by klausenbusk** [comment]
> Looks good no?

Nope, running `sed 's/bash install.sh <(cat install-{chroot,common}.sh)/bash install.sh < <(cat install-{chroot,common}.sh)/g' -i *.json` should fix the issue. Could you try that and report back?

**Comment by juadde** [comment]
OK, seems that adding the < did the trick. I was unfamiliar with this notation, at least I learned something today. I will try again the cloud.json generation later, as it seems that the problem should not occur for those images. Will you submit the PR to fix this?

**Comment by juadde** [comment]
PR submitted.

**Comment by shibumi** [comment]
Mh what is the difference between `< <()` and `<<()`? The space between both arrows looks weird.

**Comment by juadde** [comment]
From what I understood <() is actually building a file descriptor with the out of the command between ().

https://askubuntu.com/questions/678915/whats-the-difference-between-and-in-bash was actually quite useful for me to understand.
