### ISSUE TITLE
[Bug] share mount command fails with "Invalid argument"

### ISSUE THREAD

**Issue by ttwhy** [archlinux/arch-boxes#96]
i get the same issue with virtualbox as provider like https://github.com/archlinux/arch-boxes/issues/28
mounting using 
`mount -cit vboxsf vagrant /vagrant `
works. The version vagrant uses by default 
`mount -t vboxsf vagrant /vagrant`
did not in my case.

box: v2020.03.04 currently released version 
windows 10 as host system
vagrant: 2.2.7
- plugins: vagrant-vbguest 0.23.0
virtualbox: 6.0.18

**Comment by shibumi** [comment]
No issues here on Arch Linux:

```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/chris/tmp
```

vagrant version: 2.2.7
host: Arch Linux
Box: 2020.03.04

No plugins installed.

My guess is, that your plugin is the reason.
Can you try to remove vagrant-vbguest?

**Comment by ttwhy** [comment]
Yes, the vagrant plugin seems to be the cause of the problem. Thanks for the support!
